repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [--fix, --line-length=120]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive, --no-strict-optional, --ignore-missing-imports]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
          - --select=D101,D102,D103

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.365
    hooks:
    - id: pyright
