name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        pdm config python.use_venv false
        mkdir -p .mypy_cache

    - name: Cache PDM virtual environment
      uses: actions/cache@v2
      with:
        path: ~/.pdm
        key: ${{ runner.os }}-pdm-${{ hashFiles('**/pdm.lock') }}
        restore-keys: |
          ${{ runner.os }}-pdm-

    - name: Install dependencies
      run: pdm install --prod

    - name: Run pre-commit hooks
      run: pdm run pre-commit run --all-files

    - name: Run pytest
      run: pdm run pytest
